### ISSUE TITLE
Obsidian libraries built inside OneDrive don't preview some xmind files properly

### ISSUE THREAD

**Issue by billowssun** [Ssentiago/obsidian-xmind-viewer#1]

**Comment by Ssentiago** [comment]
> _No description provided._

Thanks, i'll check out it

**Comment by Ssentiago** [comment]
It's resolved?

**Comment by billowssun** [comment]
It doesn't look like it's OneDrive, I'm guessing it's something to do with the xmind version, and files created with a more recent version will have problems using this plugin.

**Comment by Ssentiago** [comment]
> It doesn't look like it's OneDrive, I'm guessing it's something to do with the xmind version, and files created with a more recent version will have problems using this plugin.

Maybe. This plugin just takes an existing file in the vault and renders it: nothing else.  But when I have the opportunity, I will look at the issues with this plugin.
