### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by merlinuwe** [Ssentiago/obsidian-xmind-viewer#2]
Thank you very much for your Obsidian xmind viewer plugin. I have lots of xmind files, made with the free release 8 available from here https://xmind.app/xmind8-pro/ which I now can integrate into Obsidian.

**Comment by Ssentiago** [comment]
> Thank you very much for your Obsidian xmind viewer plugin. I have lots of xmind files, made with the free release 8 available from here https://xmind.app/xmind8-pro/ which I now can integrate into Obsidian.

Hello! Thank you for your feedback. I'm glad you enjoyed the plugin.
